BaseProyecto/Areas/Cliente/Controllers/ArticuloController.cs
using Base.Data;
using Base.Data.Data.Repository;
using Base.Data.Data.Repository.IRepository;
using Base.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace BaseProyecto.Areas.Cliente.Controllers
{
    [Area("Cliente")]

    public class ArticuloController : Controller
    {

        private readonly IContenedorTrabajo _contenedorTrabajo;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly ApplicationDbContext _Context;

        public ArticuloController(ApplicationDbContext contexto, IContenedorTrabajo contenedor, IHttpContextAccessor contextAccessor)
        {
            _Context = contexto;
            _contenedorTrabajo = contenedor;
            httpContextAccessor = contextAccessor;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Inicio()
        {
            return View();
        }
        [Authorize]
        public IActionResult AgregarAlCarro(int idArticulo)
        {
			var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            Carrito Carro = _contenedorTrabajo.Carrito.GetFirstOrDefault(c => c.UsuarioId == userId);
            if (Carro == null)
            {
				Carro = new Carrito();
                Carro.FechaCreacion = DateTime.Now;
                Carro.UsuarioId = userId;
                _contenedorTrabajo.Carrito.Add(Carro);
                _contenedorTrabajo.Save();
			}
            CarritoArticulo Articulo=_contenedorTrabajo.CarritoArticulo.GetFirstOrDefault(a=>a.ArticuloId == idArticulo && a.CarritoId==Carro.Id);
            if (Articulo != null)
            {
                Articulo.Cantidad += 1;
                _contenedorTrabajo.CarritoArticulo.Update(Articulo);

            }
            else
            {

				Articulo = new CarritoArticulo()
				{
					CarritoId = Carro.Id,
					ArticuloId = idArticulo,
					Cantidad = 1
				};
                _contenedorTrabajo.CarritoArticulo.Add(Articulo);

            }


            _contenedorTrabajo.Save();

			return RedirectToAction("Index","Carrito");
        }
        [HttpGet]
        public IActionResult GetAll()
        {
            var art = _contenedorTrabajo.Articulo.GetAll(includeProperties: "Categoria").Where(A=>A.habilitado==1);
            foreach (var item in art)
            {
                var request = httpContextAccessor.HttpContext.Request;
                var baseURL = $"{request.Scheme}://{request.Host}";
                item.Imagen = $"{baseURL}{item.Imagen}";
            }
            
            return Json(new { data = art });
        }
        [Authorize]
		public IActionResult Detalle(int id)
        {
            var articulo = _Context.Articulo
                       .Include(a => a.Categoria)
                       .FirstOrDefault(a => a.Id == id);
            return View(articulo);
        }
    }
}

BaseProyecto/Areas/Usuario/Controllers/ArticuloController.cs
using Base.Data.Data.Repository.IRepository;
using Base.Models;
using BaseProyecto.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BaseProyecto.Areas.Usuario.Controllers
{
    [Area ("Usuario")]
	[Authorize(Roles = "Administrador")]

	public class ArticuloController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        public ArticuloController(IContenedorTrabajo Contenedor)
        {
            _contenedorTrabajo = Contenedor;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetAll()
        {
            var art = _contenedorTrabajo.Articulo.GetAll(includeProperties:"Categoria");
            return Json(new { data =  art});
        }

        [HttpGet]
        public IActionResult Create()
        {
            ArticuloVM articuloVM = new ArticuloVM()
            {
                Articulo = new Articulo(),
                ListaCategoria = _contenedorTrabajo.Categoria.GetListaCategoria()
            };

            return View(articuloVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ArticuloVM ArtiVM, IFormFile file)
        {
            
                if (file != null && file.Length > 0)
                {
                    ArtiVM.Articulo.Imagen = GuardarImagen(file);
                }
                _contenedorTrabajo.Articulo.Add(ArtiVM.Articulo);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));
            
            ArtiVM.ListaCategoria = _contenedorTrabajo.Categoria.GetListaCategoria();
            return View(ArtiVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Articulo articulo, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                if (file != null && file.Length > 0)
                {
                    articulo.Imagen = GuardarImagen(file);
                }
                _contenedorTrabajo.Articulo.Update(articulo);
                _contenedorTrabajo.Save();
                return RedirectToAction("Index");
            }
            return View(articulo);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Articulo articulo = new Articulo();
            articulo = _contenedorTrabajo.Articulo.Get(id);
            if (articulo == null)
            {
                return NotFound();
            }
            return View(articulo);
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var articulo = _contenedorTrabajo.Articulo.Get(id);
            if (articulo == null)
            {
                return Json(new { success = false, message = "Error al eliminar el Articulo" });
            }

            _contenedorTrabajo.Articulo.Remove(articulo);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Articulo eliminada exitosamente" });
        }

        private string GuardarImagen(IFormFile formFile)
        {

            if (formFile != null && formFile.Length > 0)
            {
                // Generar una ruta única para la imagen
                var fileName = Path.GetFileNameWithoutExtension(formFile.FileName);
                var extension = Path.GetExtension(formFile.FileName);
                var uniqueFileName = $"{fileName}_{Guid.NewGuid()}{extension}";

                // Ruta de almacenamiento en el sistema de archivos
                var uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "Uploads");
                if (!Directory.Exists(uploadsFolder)) //Si el directorio no existe crear uno
                {
                    Directory.CreateDirectory(uploadsFolder);
                }

                var filePath = Path.Combine(uploadsFolder, uniqueFileName);

                // Guardar la imagen en el servidor
                using (var stream = new FileStream(filePath, FileMode.Create))
                {
                    formFile.CopyToAsync(stream);
                }

                // Asignar la ruta de la imagen al producto
                return $"/Uploads/{uniqueFileName}";


            }

            return "/Uploads/default.jpeg";
        }

    }
}

BaseProyecto/Areas/Usuario/Views/Articulo/Create.cshtml
@model BaseProyecto.ViewModels.ArticuloVM

@{
    ViewData["Title"] = "Crear Nuevo Articulo";
}

<h2>Crear Nueva Categoría</h2>

<form asp-controller="Articulo" asp-action="Create" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Articulo.Nombre" class="control-label"></label>
        <input asp-for="Articulo.Nombre" class="form-control" />
        <span asp-validation-for="Articulo.Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Articulo.precio" class="control-label"></label>
        <input asp-for="Articulo.precio" class="form-control" />
        <span asp-validation-for="Articulo.precio" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Articulo.cantidad" class="control-label"></label>
        <input asp-for="Articulo.cantidad" class="form-control" />
        <span asp-validation-for="Articulo.cantidad" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Articulo.habilitado" class="control-label"></label>
        <select asp-for="Articulo.habilitado" class="form-control">
            <option value="1">Habilitado</option>
            <option value="0">Deshabilitado</option>
        </select>
        <span asp-validation-for="Articulo.habilitado" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Articulo.CategoriaId" class="control-label"></label>
        @Html.DropDownListFor(m => m.Articulo.CategoriaId, Model.ListaCategoria,
                 "-Seleccionar categoría-", new { @class = "form-control" })
        <span asp-validation-for="Articulo.CategoriaId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="file">Subir Imagen</label>
        <input type="file" class="form-control" id="file" name="file" />
    </div>
    <div class="form-group mt-3">
        <input type="submit" value="Guardar" class="btn btn-primary" />
    </div>
</form>


<div class="mt-3">
    <a asp-action="Index" class="btn btn-secondary">Volver al listado</a>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

BaseProyecto/Areas/Usuario/Views/Articulo/Edit.cshtml
@model Base.Models.Articulo

@{
    ViewData["Title"] = "Editar Articulo";
}

<h2>Editar Articulo</h2>

<form asp-action="Edit" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Nombre" class="control-label"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="precio" class="control-label"></label>
        <input asp-for="precio" class="form-control" />
        <span asp-validation-for="precio" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="cantidad" class="control-label"></label>
        <input asp-for="cantidad" class="form-control" />
        <span asp-validation-for="cantidad" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="habilitado" class="control-label"></label>
        <input asp-for="habilitado" class="form-control" />
        <span asp-validation-for="habilitado" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CategoriaId" class="control-label"></label>
        <input asp-for="CategoriaId" class="form-control" />
        <span asp-validation-for="CategoriaId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="file">Subir Imagen</label>
        <input type="file" class="form-control" id="file" name="file" />
    </div>
    <div class="form-group mt-3">
        <input type="submit" value="Guardar" class="btn btn-primary" />
    </div>
</form>

<div class="mt-3">
    <a asp-action="Index" class="btn btn-secondary">Volver al listado</a>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

BaseProyecto/Areas/Usuario/Views/Articulo/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="container mt-4">
    <div class="row">
        <div class="col-8">
            <h2>
                Lista de articulos
            </h2>
        </div>
        <div class="col-4 text-end mb-2">
            <button onclick="printTable()" class="btn btn-primary mt-3 me-2">
                Imprimir Tabla
            </button>
            <a asp-action="Create" class="btn btn-primary mt-3"><i class="fa-solid fa-plus"></i>Nuevo Articulo</a>
        </div>
    </div>
    <br />
    <br />

    <table id="tblArticulo" class="table table-striped" style="width:100%">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Cantidad</th>
                <th>Habilitado</th>
                <th>Categoria</th>
                <th>Operaciones</th>
            </tr>
        </thead>

    </table>

</div>
@section Scripts {
    <script src="~/js/Articulo.js"></script>
}