BaseProyecto/Areas/Cliente/Controllers/CarritoController.cs
using Base.Data.Data.Repository.IRepository;
using Base.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BaseProyecto.Areas.Cliente.Controllers
{
    [Area("Cliente")]
	public class CarritoController : Controller
	{
		private readonly IContenedorTrabajo _contenedorTrabajo;
		private readonly IHttpContextAccessor httpContextAccessor;

		public CarritoController(IContenedorTrabajo contenedor, IHttpContextAccessor contextAccessor)
        {
			_contenedorTrabajo= contenedor;
			httpContextAccessor = contextAccessor;

		}
        public IActionResult Index()
		{
			return View();
		}

		public IActionResult GetAll()
		{
			var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
			var carro= _contenedorTrabajo.Carrito.GetFirstOrDefault(x=>x.UsuarioId==userId);
			if(carro==null)return RedirectToAction("Index","Articulo");

			var carritoArticulos = _contenedorTrabajo.CarritoArticulo
						  .GetAll(x => x.CarritoId == carro.Id, includeProperties: "Articulo") // Filtrar por CarritoId
						  .ToList(); 
			foreach (var item in carritoArticulos)
			{
				var request = httpContextAccessor.HttpContext.Request;
				var baseURL = $"{request.Scheme}://{request.Host}";
				item.Articulo.Imagen = $"{baseURL}{item.Articulo.Imagen}";
			}

			return Json(new { data = carritoArticulos });
		}

        // Acción para eliminar un artículo del carrito
        [HttpPost]
        public IActionResult Eliminar(int id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var carro = _contenedorTrabajo.Carrito.GetFirstOrDefault(x => x.UsuarioId == userId);

            if (carro != null)
            {
                var carritoArticulo = _contenedorTrabajo.CarritoArticulo.GetFirstOrDefault(x=>x.Id == id);
                if (carritoArticulo != null)
                {
                    _contenedorTrabajo.CarritoArticulo.Remove(carritoArticulo);
                    _contenedorTrabajo.Save();
                }
            }

            return Json(new { success = true });
        }

        // Acción para realizar la compra (vaciar el carrito)
        [HttpPost]
        public IActionResult RealizarCompra()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var carro = _contenedorTrabajo.Carrito.GetFirstOrDefault(x => x.UsuarioId == userId);

            if (carro != null)
            {
                var carritos = _contenedorTrabajo.CarritoArticulo.GetAll(x => x.CarritoId == carro.Id);
                foreach (var item in carritos)
                {
                    var articulo = _contenedorTrabajo.Articulo.Get(item.ArticuloId);
                    if (articulo.cantidad >= item.Cantidad)
                    {
                        articulo.cantidad -= item.Cantidad;
                        _contenedorTrabajo.CarritoArticulo.Remove(item);
                    }
                    else
                    {
                        // Retorna un error indicando que no hay suficiente stock
                        return BadRequest(new { success = false, mensaje = $"No hay stock suficiente para {articulo.Nombre}." });
                    }
                }
                _contenedorTrabajo.Save();
                return Json(new { success = true });
            }

            return Json(new { success = false, mensaje = "Carrito no encontrado." });
        }


    }
}

BaseProyecto/Areas/Usuario/Controllers/CategoriaController.cs
using Base.Data.Data.Repository;
using Base.Data.Data.Repository.IRepository;
using Microsoft.AspNetCore.Mvc;
using Base.Models;
using Microsoft.AspNetCore.Authorization;

namespace BaseProyecto.Areas.Usuario.Controllers
{
    [Area("Usuario")]
	[Authorize(Roles = "Administrador")]

	public class CategoriaController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        public CategoriaController(IContenedorTrabajo Contenedor)
        {
            _contenedorTrabajo = Contenedor;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetAll()
        {
            return Json(new { data = _contenedorTrabajo.Categoria.GetAll() });
        }

        [HttpGet]
		public IActionResult Create()
        {


            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

		public IActionResult Create(Categoria categoria)
        {
            if (ModelState.IsValid)
            {
                _contenedorTrabajo.Categoria.Add(categoria);
                _contenedorTrabajo.Save();
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Categoria categoria) 
        {
            if (ModelState.IsValid) 
            {
                _contenedorTrabajo.Categoria.Update(categoria);
                _contenedorTrabajo.Save();
                return RedirectToAction("Index");
            }
            return View(categoria);
        }

        [HttpGet]
        public IActionResult Edit(int id) 
        {
            Categoria categoria = new Categoria();
            categoria=_contenedorTrabajo.Categoria.Get(id);
            if (categoria == null)
            {
                return NotFound();
            }
            return View(categoria);
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var categoria = _contenedorTrabajo.Categoria.Get(id);
            if (categoria == null)
            {
                return Json(new { success = false, message = "Error al eliminar la categoría" });
            }

            _contenedorTrabajo.Categoria.Remove(categoria);
            _contenedorTrabajo.Save();
            return Json(new { success = true, message = "Categoría eliminada exitosamente" });
        }

    }
}

BaseProyecto/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BaseProyecto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BaseProyecto.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.10.5/sweetalert2.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">

    <style>
        /* Fondo degradado personalizado para toda la página */
        body {
            background: linear-gradient(to bottom, #ff7e5f, #feb47b); /* Degradado de naranja */
            min-height: 100vh;
        }

        /* Barra de navegación personalizada */
        header .navbar {
            background: rgba(255, 255, 255, 0.85); /* Fondo semitransparente para la barra */
        }

        /* Fondo de la barra de navegación donde está "GYMSTORE" y "Articulos" */
        .navbar-brand {
            color: #ff7e5f !important; /* Color del logo "GYMSTORE" */
        }

        .nav-link {
            color: #feb47b !important; /* Color de los enlaces en la barra de navegación */
        }

            .nav-link:hover {
                color: #ff7e5f !important; /* Color al pasar el ratón sobre los enlaces */
            }

        /* Fondo de la sección de footer */
        footer {
            background: rgba(255, 255, 255, 0.85); /* Fondo semitransparente */
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="Cliente" asp-controller="Articulo" asp-action="Inicio">GYMSTORE</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Cliente" asp-controller="Articulo" asp-action="Index">Articulos</a>
                            </li>
                        }
                        @if (User.IsInRole("Administrador"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Usuario" asp-controller="Articulo" asp-action="Index">Articulos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Usuario" asp-controller="Usuario" asp-action="Index">Usuario</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Usuario" asp-controller="Categoria" asp-action="Index">Categoria</a>
                            </li>
                        }
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Cliente" asp-controller="Articulo" asp-action="Index">Articulos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Cliente" asp-controller="Carrito" asp-action="Index">Carrito</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <p style="color: #ff7e5f;">&copy; 2024 - BaseProyecto - <a href="#" style="color: #feb47b;">Privacy</a></p>
        </div>
    </footer>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.0/js/dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/3.2.1/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.10.5/sweetalert2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BaseProyecto/Views/Shared/_LayoutCliente.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BaseProyecto</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BaseProyecto.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.0.0/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.10.5/sweetalert2.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BaseProyecto</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BaseProyecto - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/2.0.0/js/dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/3.2.1/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert2/11.10.5/sweetalert2.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>